services:
  web:
    build:
      context: .
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY}
    container_name: web_ne_app
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-ne.rule=Host(`xn--nuevaespaa-19a.eu`) || Host(`www.xn--nuevaespaa-19a.eu`)"
      - "traefik.http.routers.web-ne.entrypoints=web,websecure"
      - "traefik.http.routers.web-ne.tls.certresolver=myresolver"
      - "traefik.http.services.web-ne.loadbalancer.server.port=3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY}
    networks:
      - web_network

networks:
  web_network:
    external: true
